### ISSUE TITLE
Shellesc issue

### ISSUE THREAD

**Issue by acad2** [T-F-S/csvsimple#1]
With the latest version of csvsimple on WIndows 10, I am getting an error, "File `shellesc.sty' not found. ^^M". However, with older (1.12) version, it is working properly. Is this a bug?

**Comment by T-F-S** [comment]
No, this is not a bug. The current version of `csvsimple` relies on the recommended `shellesc` package which is (now) part of the standard packages. You may need to update your TeX installation to have it on your system.
