### ISSUE TITLE
separator = space

### ISSUE THREAD

**Issue by lvjr** [T-F-S/csvsimple#20]
At this time, option `separator = space` is missing. Package `pgfplotstable` allows users to set space as separator. It would be nice if `csvsimple` would aslo have this option.

**Comment by T-F-S** [comment]
I'm not sure if this is possible by extending the current implementation as it is, but I will look into it (with more time).

**Comment by T-F-S** [comment]
Option setting `separator = space` added:
https://github.com/T-F-S/csvsimple/releases/tag/v2.4.0
