### ISSUE TITLE
Allow filter appending

### ISSUE THREAD

**Issue by Krzmbrzl** [T-F-S/csvsimple#24]
Let me start by stating: The possibility to filter input data is superb!

Now, I believe that it would be even more handy if one could append filters. E.g.
```latex
\csvreader[
    filter strcmp = {\mycol}{bla},
    filter strcmp = {\myothercol}{blubb},
]{...}{...}
```
which should essentially become a filter á la
```c
if (mycol == "bla" && myothercol == "blubb") {
    accept
} else {
    reject
}
```

As it stands, the second invocation of `filter strcmp` will overwrite the first.

**Comment by T-F-S** [comment]
Such filtering could be done `filter bool`, but this needs expl3 syntax.

Your suggestion would be easier to use. But, I would not make the existing filters appending, but rather introduce new options like `and filter strcmp`:

```latex
\csvreader[
    filter strcmp = {\mycol}{bla},
    and filter strcmp = {\myothercol}{blubb},
]{...}{...}
```

This needs some change of the existing code, but first tests look promising.

**Comment by Krzmbrzl** [comment]
> Such filtering could be done filter bool, but this needs expl3 syntax.

It's also possible with `filter expr` and `etoolbox` - that's what I use for the time being.

> But, I would not make the existing filters appending, but rather introduce new options like and filter strcmp

Yeah, sounds good to me :+1:

**Comment by T-F-S** [comment]
New additive filter options added:
https://github.com/T-F-S/csvsimple/releases/tag/v2.4.0
