### ISSUE TITLE
[question] How to reduce digits after dot?

### ISSUE THREAD

**Issue by Freed-Wu** [T-F-S/csvsimple#26]
I have searched the texdoc but found nothing related. I hope something like
```tex
  \csvautobooktabular[respect percent, digit number=2]{a.csv}
```

TIA!

**Comment by T-F-S** [comment]
Transforming the csv content is outside the scope of the package.

But, you may use the `siunitx` package for number formatting. You find several examples inside the `csvsimple-l3` documentation from page 48 on how to use `\tablenum` from  `siunitx`.
