### ISSUE TITLE
Missing doublequote support hidden in documentation

### ISSUE THREAD

**Issue by lemzwerg** [T-F-S/csvsimple#3]
It really took me *hours* to find out that csvsimple doesn't support the standard CSV notation for quoting, i.e., the use of paired double quotes.  Neither is there a single example in the beginning of the manual that demonstrates the use of `{` and `}`, nor is there any warning that `"..."` can fail *silently* because csvsimple ignores lines that it cannot parse.

Please adapt section 'First Steps' accordingly.

**Comment by T-F-S** [comment]
The second line of 'First Steps' gives a positive mention that curly braces can be used for quoting. I can add a warning that other kinds of quotation like double quotes are not supported.

**Comment by lemzwerg** [comment]
Yes, please.  And ideally at least one example gets slightly massaged to demonstrate `{` and `}` also.

**Comment by T-F-S** [comment]
Introduction of v1.21 extended with caveats for csv file format.

**Comment by lemzwerg** [comment]
Herzlichen Dank!

However, this sentence from the documentation
```
Values are expected to be not quoted or quoted with curly braces |{}|
```
is ambiguous.  I suggest that it gets replaced with something like the following.
```
Values are expected to be either not quoted or quoted with curly braces |{}|
```

**Comment by T-F-S** [comment]
OK, I will add the word `either` for the next version.
