### ISSUE TITLE
docs: `\ifcsvstrcmp` is always available in `csvsimple-l3`

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/csvsimple#33]
Although it's true for `csvsimple-legacy`, in `csvsimple-l3` `\ifcsvstrcmp` is always available. Thus the (general) description of `\ifcsvstrcmp` and `\ifcsvstrequal` at the beginning of `csvsimple-l3.pdf` (2.6.0pre2, 2023-12-18), sec. 5 "String and Number Tests" need some adaption.

https://github.com/T-F-S/csvsimple/blob/3f4d4295b7fa2395758f4d1b49d67603d1cde9b0/doc/latex/csvsimple/csvsimple-l3.tex#L2367-L2381

In `csvsimple-l3.sty`, `\ifcsvstrcmp` always uses `\str_if_eq:eeTF`.
https://github.com/T-F-S/csvsimple/blob/3f4d4295b7fa2395758f4d1b49d67603d1cde9b0/tex/latex/csvsimple/csvsimple-l3.sty#L477-L480

In `csvsimple-legacy.sty`, `\ifcsvstrcmp` might fallback to `\ifcsvstrequal`
https://github.com/T-F-S/csvsimple/blob/3f4d4295b7fa2395758f4d1b49d67603d1cde9b0/tex/latex/csvsimple/csvsimple-legacy.sty#L776-L793

**Comment by muzimuzhi** [comment]
The first paragraph in `csvsimple-l3.pdf` (2.6.0pre2, 2023-12-18), sec. 5 "String and Number Tests" is not 100% correct too, since now these tests are wrappers of `expl3` functions.

> The following string tests are complementing the string tests from packages like `etoolbox`. They all do the same, i.e., comparing expanded strings for equality. To some extent, they are provided for backward compatibility.

**Comment by T-F-S** [comment]
I have updated the documentation and removed the old stuff. Thank you for the hint.

**Comment by T-F-S** [comment]
Done with https://github.com/T-F-S/csvsimple/releases/tag/v2.6.0
