### ISSUE TITLE
XML entities as elements

### ISSUE THREAD

**Issue by jsbien** [T-F-S/csvsimple#35]
I would like to typeset a file which contains lines like this:
`2E4B;⹋;_symbols;"&tridagger;";1;;;"A 27";4.x;"TRIPLE DAGGER";;0;;"2023-04-30 12:08:56";https://mufi.info/q.php?p=mufi/chars/unichar/11851`
There is no problem in changing the category of `_` and `&`, but the quoted semicolon is treated as a separator. Any suggestions how to circumvent the problem? I don't have to typeset the file as is, I can do some simple preprocessing.

P.S. Please activate the Discussions tab.

**Comment by muzimuzhi** [comment]
Change to another separator in preprocessing in some non-TeX language? If none of the pre-defined list of separators (`/csvsim/separator={comma|semicolon|pipe|tab|space}`) are useable, you can specify your own by `\tl_gset:Nn \g__csvsim_separator_tl {<new separator>}`.

Also if it's already possible to preprocess the file content, then for simple display purposes you can directly output in TeX tabular markup, hence skip the read-in-as-csv step.

**Comment by jsbien** [comment]
Thanks for all suggestion!
