### ISSUE TITLE
Comment lines in CSV file

### ISSUE THREAD

**Issue by eisenlohr** [T-F-S/csvsimple#40]
As far as I can tell, there is presently no way to filter out (leading) comment lines from a CSV file. It would be helpful to have such functionality, i.e. ability to specify a character that renders a line a comment.

Example:

```
# This data was taken from source
year,count
2000,123
2010,444
2020,341
```

**Comment by muzimuzhi** [comment]
From `csvsimple-l3` package manual (v2.6.1 2024-05-16), sec 4.7,

> Be default, the CSV content is treated like normal LaTeX text, 

so by default `%` can be used to start an in-line comment, and by playing with catcode of `#` you can use `#` to start an in-line comment too.

Note that in `csvsimple-l3` v2.6.1, commented lines _before_ header line is not supported, see #41.

```tex
\begin{filecontents}[noheader, force]{test-percent-comment.csv}
% comment
year,count
% comment
2000,123
2010,444
2020,341
\end{filecontents}

\begin{filecontents}[noheader, force]{test-sharp-comment.csv}
# comment
year,count
# comment
2000,123
2010,444
2020,341
\end{filecontents}

\documentclass{article}
\usepackage{csvsimple-l3}

% temp patch to skip blank lines before the header line
% see https://github.com/T-F-S/csvsimple/issues/41
\ExplSyntaxOn
\cs_undefine:N \__csvsim_read_head:
\cs_new_protected_nopar:Npn \__csvsim_read_head:
  {
    % <<< new
    \bool_do_while:nn { \tl_if_blank_p:o \csvline }
      { \__csvsim_read_line: }
    % ===
    % \__csvsim_read_line:
    % >>> old
    \tl_if_eq:NNTF \csvline \c__csvsim_par_tl
      {
        \msg_error:nne { csvsimple }{ empty-head }{ \g__csvsim_filename_str }
      }
      {
        \int_gzero:N \g_csvsim_columncount_int
        \__csvsim_scan_line:
        \bool_if:NT \g__csvsim_colnames_detection_bool
          {
            \int_step_function:nN \g_csvsim_columncount_int \__csvsim_process_head_name:n
          }
      }
  }

\cs_new_protected:Npn \ResetCctab
  { \cctab_select:N \c_document_cctab }
\ExplSyntaxOff

\begin{document}
\csvautotabular{test-percent-comment.csv}

\catcode`\#=\the\catcode`\%
\csvautotabular{test-sharp-comment.csv}
\ResetCctab
\end{document}
```
output
![image](https://github.com/user-attachments/assets/c5734dfc-a1b7-404a-a794-4ca8cf693009)

**Comment by eisenlohr** [comment]
Thank you for pointing out the sentence at the start of section 4.7 in the [documentation](http://mirrors.ctan.org/macros/latex/contrib/csvsimple/csvsimple-l3.pdf). I only searched the manual for the keyword "comment" and found no mention...

**Comment by muzimuzhi** [comment]
The example in package manual (v2.6.1), sec. 7.1 A Serial Letter shows use of `%` as comment char, but unfortunately the word "comment" is not mentioned.
